/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaccinesRouteImport } from './routes/vaccines'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonsIndexRouteImport } from './routes/persons.index'
import { Route as PersonsPersonIdRouteImport } from './routes/persons.$personId'

const VaccinesRoute = VaccinesRouteImport.update({
  id: '/vaccines',
  path: '/vaccines',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonsRoute,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PersonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/persons': typeof PersonsRouteWithChildren
  '/vaccines': typeof VaccinesRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons/': typeof PersonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vaccines': typeof VaccinesRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons': typeof PersonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/persons': typeof PersonsRouteWithChildren
  '/vaccines': typeof VaccinesRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons/': typeof PersonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/persons' | '/vaccines' | '/persons/$personId' | '/persons/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vaccines' | '/persons/$personId' | '/persons'
  id:
    | '__root__'
    | '/'
    | '/persons'
    | '/vaccines'
    | '/persons/$personId'
    | '/persons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonsRoute: typeof PersonsRouteWithChildren
  VaccinesRoute: typeof VaccinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaccines': {
      id: '/vaccines'
      path: '/vaccines'
      fullPath: '/vaccines'
      preLoaderRoute: typeof VaccinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof PersonsRoute
    }
  }
}

interface PersonsRouteChildren {
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
}

const PersonsRouteChildren: PersonsRouteChildren = {
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  PersonsIndexRoute: PersonsIndexRoute,
}

const PersonsRouteWithChildren =
  PersonsRoute._addFileChildren(PersonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonsRoute: PersonsRouteWithChildren,
  VaccinesRoute: VaccinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
